recursive: true
extension: ['coffee', 'ts', 'mjs', 'js', 'cjs']
ui: bdd
colors: true
#node-option:
#  - experimental-specifier-resolution=node
  #- loader=ts-node/esm
#loader:
#  - ts-node/esm
  #- coffeescript/register.js
require:
  - coffeescript/register.js
  - ts-node/register
  #- ./test/main.coffee
  #- coffee-coverage/register
#file: test/main.coffee
spec: ./test/lib/*.spec.coffee
